### ISSUE TITLE
System.NullReferenceException , return Right.Stream;

### ISSUE THREAD

**Issue by MicroJOo** [jakobharder/burntime#7]
when im trying to debug the "launcher"  with VisualStudio Community 2015 this is what i get : 

![burn bug 1](https://cloud.githubusercontent.com/assets/9139965/9704444/0c34bc2a-54a7-11e5-9af1-df2562765bdf.png)

(placing the burntime-files into "bin/burntime/game/Burntime" before building , doesnt help

**Comment by MicroJOo** [comment]
@jakobharder : sos ... :D

**Comment by jakobharder** [comment]
Hi MicroJOo, can you go a little up in the call stack? Obviously some file was missing, but what that would be interesting. On Friday I have a bit more time to take a closer look at it myself.

**Comment by MicroJOo** [comment]
![callstack2](https://cloud.githubusercontent.com/assets/9139965/9760377/d66b8e8e-56f4-11e5-9902-5119f5fb1b13.png)

**Comment by jakobharder** [comment]
Not sure what exactly happened, but the lang.txt is from one of the launcher packages. Which actually only exists in the form of lang-EN.txt and so on. So the language setting must have gotten wrong somehow. No idea why yet though

**Comment by jakobharder** [comment]
The launcher packages must have been not available in the path.
The post-build command was missing for the Launcher. That's why it worked after building the game once.
Fixed in bbe36acb4073e9f73d002989f19fd98ee902a029
And added proper checks for missing launcher files in 438de0ace37cf6c5a67f163a6736394929802f31
